/* eslint-disable */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ClickNShip",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
{
  return (
    <html lang="en">
        <head>
        <script src="https://kit.fontawesome.com/d576c738e8.js" crossOrigin="anonymous"></script>
        </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
